# Application Source: https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-dotnetcore-sqldb
variables:
  vmImage: 'ubuntu-latest'

#another way to show the same thing 
#applicationName: 'todo'
- name: applicationName
  value: 'todo'

#using variable groups
#majorVersion: 1
#minorVersion: 0
- group: 'version_numbers'



# Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml
name: $(BuildDefinitionName)_$(SourceBranchName)_$(majorVersion).$(minorVersion)$(Rev:.r)

stages:

- stage: BLD
  displayName: Build(CI)
  #this can be a global variable as well
  variables: {buildConfiguration: 'Release'}
  jobs:

  - job: Infrastructure
    pool:
      vmImage: $(vmImage)
    steps:
    - script: echo "Running the Infrastructure build for $(applicationName)"
      displayName: 'Starup'
    - template: 'pipelines/infrastructure/build.yml'

  - job: Application
    pool:
      vmImage: $(vmImage)
    dependsOn: Infrastructure
    steps:
    #this is to explain that you can run a task in the same file
    - script: echo "Running the Application build for $(applicationName)"
      displayName: 'Starup'
    #this is to explain that you can use a template
    - template: 'pipelines/application/build.yml'
      parameters: {buildConfiguration: $(buildConfiguration)}