variables:
- group: 'version_numbers'
#these are defined using variable groups
#majorVersion: 1
#minorVersion: 0
- name: vmImage
  value: 'ubuntu-latest'
- name: applicationName
  value: 'todo'
#there is another way if you are interested
#'Click Edit > Variables'

# Reference: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/run-number?view=azure-devops&tabs=yaml
name: $(BuildDefinitionName)_$(SourceBranchName)_$(majorVersion).$(minorVersion)$(Rev:.r)

stages:

- stage: BLD
  displayName: Build(CI)
  #this can be a global variable as well
  variables: {buildConfiguration: 'Release'}
  jobs:

  - job: Application
    pool:
      vmImage: $(vmImage)
    #this won't run before Infrastructure, comment the dependsOn to run the jobs simultaneously
    dependsOn: Infrastructure
    steps:
    #this is to explain that you can run a task in the same file
    - script: echo "Running the Application build for $(applicationName)"
      displayName: 'Starup'
    #this is to explain that you can use a template
    - template: 'pipelines/application/build.yml'
      parameters: {buildConfiguration: $(buildConfiguration)}

  - job: Infrastructure
    pool:
      vmImage: $(vmImage)
    steps:
    - script: echo "Running the Infrastructure build for $(applicationName)"
      displayName: 'Starup'
    - template: 'pipelines/infrastructure/build.yml'